// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:180198123750:web:c5d08aaec2edf2b5e4b327',
    messagingSenderId: '180198123750',
    projectId: 'gramurjaappflutter',
    authDomain: 'gramurjaappflutter.firebaseapp.com',
    storageBucket: 'gramurjaappflutter.appspot.com',
    measurementId: 'G-LSWT14WKNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:180198123750:android:6c7bc46ee837d716e4b327',
    messagingSenderId: '180198123750',
    projectId: 'gramurjaappflutter',
    storageBucket: 'gramurjaappflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:180198123750:ios:0b965cc17f88e383e4b327',
    messagingSenderId: '180198123750',
    projectId: 'gramurjaappflutter',
    storageBucket: 'gramurjaappflutter.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:180198123750:ios:0b965cc17f88e383e4b327',
    messagingSenderId: '180198123750',
    projectId: 'gramurjaappflutter',
    storageBucket: 'gramurjaappflutter.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:180198123750:web:ffe2a948e1c48de4e4b327',
    messagingSenderId: '180198123750',
    projectId: 'gramurjaappflutter',
    authDomain: 'gramurjaappflutter.firebaseapp.com',
    storageBucket: 'gramurjaappflutter.appspot.com',
    measurementId: 'G-Y0J9L6Y3ZK',
  );
}
